### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by FaZoREX** [reirep/matcp-java#1]

**Comment by reirep** [comment]
If you're still having this  issue, don't hesitate to reopen a ticket :) Will help with great pleasure.

**Comment by FaZoREX** [comment]
thank you.
I have a question and that is how can I install this java API on a linux kernel directly. currently I have it installed on a vagrantbox. is there a way to install it directly on a mptcp-enabled linux system?
I tried to compile this version of the kernel https://github.com/hoang-tranviet/mptcp/tree/mptcp_v0.91_api_cleanup that I was told it contains a working API of native c where I can then install the java API on it, but I could not compile that kernel due to some errors.

**Comment by reirep** [comment]
To use this java API on a mptcp aware linux kernel directly, you need to have a compiled and functional linux kenel (cannot help you with that, sorry), you have install on it (with your favorite packet manager) java 7 or higher (you'll need the jdk and jre). Use the makefile to compile the java shared library that will act as a bridge between the native C API and java (to see how to manipulate the mptcp functionnality with java see Usage.java https://github.com/reirep/mptcp-java/blob/master/Usage.java ). If you kernel is not mptcp enabled, a crash will occur during the runtime. 
I plan on redesigning this little projet when I got the time . I thinbk that using the reflexion to extract the socket may be a good idea instead of using internal (not intended for that) java call.
